API_KEY = "JOHN987"

SCAM_KEYWORDS = [
    "100%free",
    "act now",
    "account blocked",
    "account compromised",
    "immediately",
    "guaranteed results",
    "urgent/act now",
    "confirm your account",
    "free gift",
    "click here",
    "limited time offer",
    "blocked",
    "verify",
    "urgent",
    "upi",
    "otp",
    "kyc",
    "suspend",
    "winner",
    "prize",
    "cash award",
    "kyc expired",
    "account suspended",
    "verify otp",
    "payment pending",
    "transaction failed",
    "reward points",
    "lottery winner",
    "unauthorized transaction",
    "suspicious activity",
    "temporary block",
    "mandatory update",
    "claim your prize",
    "refund processed",
    "payment failed",
    "pending kyc",
    "customer care number",
    "screen sharing app",
    "download apk",
    "security alert",
    "identity verification",
    "bank executive",
    "legal action",
    "court notice",
    "police case",
    "electricity disconnected",
    "bill unpaid",
    "sim block",
    "porting request",
    "gift voucher",
    "redeem points",
    "tax refund",
    "investment opportunity",
    "double your money",
    "work from home",
    "part time job",
    "earn daily",
    "verified seller",
    "advance payment",
    "security deposit",
    "wallet blocked",
    "upi pin required",
    "scan qr code",
    "linked bank account",
    "mobile number change",
    "net banking login",
    "password reset link",
    "verify identity now",
    "account validation",
    "suspicious login attempt",
    "high risk transaction",
    "urgent attention required",
]

NORMAL_REPLIES = [
    "Okay",
    "Noted",
    "Sure",
    "I'll check",
    "Thanks for letting me know",
    "I see",
    "Got it",
    "Understood",
    "Will do",
    "Thank you",
    "Fine",
    "No problem",
    "Alright",
    "I'll look into it",
    "Good morning",
    "Have a nice day",
    "Yes",
    "No",
    "Maybe later",
    "I am busy right now",
    "Talk to you later",
    "Sounds good",
    "Please send it",
    "I'll be there",
    "Great",
    "Let me think",
    "I'm not sure",
    "I'll get back to you",
    "Okay, thanks",
    "No worries",
    "That's fine",
    "Cool",
    "Okay, I'll see",
    "Just a moment",
    "I'm checking",
    "One second",
    "Will check later",
    "Please wait",
    "I'll call you",
    "Let's see",
    "I'm on it",
    "Perfect",
    "Done",
    "Will update you",
    "Please confirm",
    "Acknowledged",
    "Received",
    "Thanks",
    "Ok",
    "No thanks",
]

SCAM_REPLIES = [
    "I don't understand, what do I need to do?",
    "Which account are you talking about?",
    "I'm trying to follow the steps but I'm stuck",
    "Where can I find my customer ID?",
    "Can you explain this again please?",
    "I'm a bit confused, is this mandatory?",
    "What happens if I don't do it right now?",
    "I just got this message, what should I do next?",
    "Is there a link I need to click?",
    "Could you walk me through the process?",
    "I'm not very tech-savvy, can you help?",
    "Which bank is this for?",
    "I have multiple accounts, which one is affected?",
    "I can't find the option you're mentioning",
    "Is there a deadline for this?",
    "Should I call someone?",
    "What information do you need from me?",
    "I'm worried about my account, is it safe?",
    "Can you send the link again?",
    "I'm seeing an error message, what does it mean?",
    "How do I verify my identity?",
    "I'm trying to open the app but it's slow",
    "Do I need my card for this?",
    "Wait, I need to find my charger",
    "Can you wait a minute while I check?",
    "I'm at work, can we do this quickly?",
    "What's the next step?",
    "I don't see any notification in my app",
    "Are you from the main branch?",
    "How long will this take?",
    "I'm worried about my balance",
    "Is this regarding the recent transaction?",
    "I don't have my passbook with me, is that okay?",
    "Can I do this from my laptop?",
    "I am unable to see the QR code",
    "Where do I need to type the numbers?",
    "Is this the only way to fix it?",
    "I'm a bit nervous, what do I do?",
    "Can you tell me which number is registered?",
    "I'm following your instructions, now what?",
    "Is there anyone else I should talk to?",
    "I don't want my account to be closed",
    "What is a KYC update?",
    "I didn't receive any email about this",
    "Can you help me with the login?",
    "I'm confused about the OTP, where does it come from?",
    "Should I share the screen?",
    "Is this related to my credit card?",
    "I just want to make sure I'm doing this right",
    "What should I click on first?",
]

